ステップ,ツール,目的,評価
1. データクリーニング,Python (Pandas),欠損値処理、データ型変換、特徴量エンジニアリングなど。,必須かつ最適。 大量のデータや複雑な処理に強い。
2. EDAと仮説構築,Tableau,データの分布、トレンド、相関を視覚的に探索し、ビジネス上の洞察（仮説）を立てる。,非常に効果的。 対話的な操作で迅速に仮説を生成できる。
3. 仮説の検証,Python (Scikit-learnなど),機械学習モデルを構築し、仮説（例: A群の顧客は解約しやすい）が統計的に正しいか、予測可能かを検証する。,最適。 統計的妥当性と予測精度を評価するために不可欠。
4. 知見のダッシュボード化,Tableau,MLモデルの結果（例: 特徴量の重要度、セグメント別の予測確率）を組み込み、具体的なアクションプランを提示するストーリーを作成する。,最適。 複雑な結果を非技術者向けに分かりやすく伝え、ビジネス上の価値を最大化する。

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data/Hotel Reservations.csv")

In [5]:
df.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

In [6]:
df.columns

Index(['Booking_ID', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'market_segment_type', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests', 'booking_status'],
      dtype='object')

In [7]:
カラム名 (英語),日本語訳,推測されるデータの意味
Booking_ID,予約ID,各予約を一意に識別する番号。
no_of_adults,大人（宿泊客）の数,予約に含まれる大人の人数。
no_of_children,子供（宿泊客）の数,予約に含まれる子供の人数。
no_of_weekend_nights,週末の宿泊数,予約に含まれる週末（金・土）の夜数。
no_of_week_nights,平日の宿泊数,予約に含まれる平日（日～木）の夜数。
type_of_meal_plan,食事プランの種類,予約された食事タイプ（例：朝食のみ、オールインクルーシブなど）。
required_car_parking_space,必要な駐車スペース,駐車場が必要かどうかのブール値（0/1）。
room_type_reserved,予約された部屋のタイプ,実際に予約された部屋のカテゴリー。
lead_time,リードタイム,予約日から到着日までの日数（予約がどれだけ前にされたか）。
arrival_year,到着年,宿泊開始の年。
arrival_month,到着月,宿泊開始の月。
arrival_date,到着日,宿泊開始の日。
market_segment_type,マーケットセグメントの種類,予約が成立した経路（例：オンライン旅行代理店(OTA)、直接予約、団体など）。
repeated_guest,リピーター客,過去にも宿泊歴があるかどうかのブール値（0/1）。
no_of_previous_cancellations,過去のキャンセル回数,過去の予約でキャンセルした回数。
no_of_previous_bookings_not_canceled,過去のキャンセルされなかった予約数,過去の予約で正常に宿泊した回数。
avg_price_per_room,部屋あたりの平均価格,1泊あたりの平均価格（税込み）。
no_of_special_requests,特別リクエストの数,予約に含まれる特別要望（例：禁煙室、ベビーベッドなど）の数。
booking_status,予約ステータス,目的変数となることが多い、予約の結果（例：キャンセル済み、チェックアウト済み）。

SyntaxError: invalid character '。' (U+3002) (2509088351.py, line 2)

In [8]:
new_columns = {
"Booking_ID":"予約ID",
"no_of_adults":"大人の数",
"no_of_children":"子供の数",
"no_of_weekend_nights":"週末の宿泊数",
"no_of_week_nights":"平日の宿泊数",
"type_of_meal_plan":"食事プランの種類",
"required_car_parking_space":"駐車場の要不要",
"room_type_reserved":"予約された部屋のタイプ",
"lead_time":"予約日から到着日までの日数",
"arrival_year":"到着年",
"arrival_month":"到着月",
"arrival_date":"到着日",
"market_segment_type":"マーケットセグメント",
"repeated_guest":"リピーター客",
"no_of_previous_cancellations":"過去のキャンセル回数",
"no_of_previous_bookings_not_canceled":"過去のキャンセルされなかった予約数",
"avg_price_per_room":"一泊あたりの宿泊費",
"no_of_special_requests":"特別リクエストの数",
"booking_status":"予約ステータス",
}

In [9]:
df_renamed = df.rename(columns=new_columns)
df_renamed.head()

,予約ID,大人の数,子供の数,週末の宿泊数,平日の宿泊数,食事プランの種類,駐車場の要不要,予約された部屋のタイプ,予約日から到着日までの日数,到着年,到着月,到着日,マーケットセグメント,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,特別リクエストの数,予約ステータス
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

In [10]:
df_renamed.iloc[492]

予約ID                     INN00493
大人の数                            2
子供の数                            0
週末の宿泊数                          2
平日の宿泊数                          5
食事プランの種類              Meal Plan 1
駐車場の要不要                         0
予約された部屋のタイプ           Room_Type 1
予約日から到着日までの日数                  98
到着年                          2018
到着月                             4
到着日                            30
マーケットセグメント                 Online
リピーター客                          0
過去のキャンセル回数                      0
過去のキャンセルされなかった予約数               0
一泊あたりの宿泊費                  109.81
特別リクエストの数                       0
予約ステータス              Not_Canceled
Name: 492, dtype: object

In [11]:
import pandas as pd
df_renamed['到着年/月/日'] = (
    df_renamed['到着年'].astype(str) + '-' + 
    df_renamed['到着月'].astype(str) + '-' + 
    df_renamed['到着日'].astype(str)
)

In [12]:
df_renamed.head()

,予約ID,大人の数,子供の数,週末の宿泊数,平日の宿泊数,食事プランの種類,駐車場の要不要,予約された部屋のタイプ,予約日から到着日までの日数,到着年,到着月,到着日,マーケットセグメント,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,特別リクエストの数,予約ステータス,到着年/月/日
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled,2017-10-2
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled,2018-11-6
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled,2018-2-28
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled,2018-5-20
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled,2018-4-11

In [13]:
df_renamed["到着年/月/日"]

0         2017-10-2
1         2018-11-6
2         2018-2-28
3         2018-5-20
4         2018-4-11
            ...
36270      2018-8-3
36271    2018-10-17
36272      2018-7-1
36273     2018-4-21
36274    2018-12-30
Name: 到着年/月/日, Length: 36275, dtype: object

In [14]:
df_renamed["到着年/月/日"] = pd.to_datetime(df_renamed["到着年/月/日"],errors="coerce")
#df_renamed[["到着年","到着月","到着日"]].drop(axis=1,inplace=True)

In [15]:
df_renamed.drop(columns=["到着年","到着月","到着日"],axis=1,inplace=True)

In [16]:
df_renamed.head()

,予約ID,大人の数,子供の数,週末の宿泊数,平日の宿泊数,食事プランの種類,駐車場の要不要,予約された部屋のタイプ,予約日から到着日までの日数,マーケットセグメント,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,特別リクエストの数,予約ステータス,到着年/月/日
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,65.00,0,Not_Canceled,2017-10-02
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,Not_Canceled,2018-11-06
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,Online,0,0,0,60.00,0,Canceled,2018-02-28
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,Online,0,0,0,100.00,0,Canceled,2018-05-20
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,Online,0,0,0,94.50,0,Canceled,2018-04-11

In [17]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [18]:
df_renamed.head()

,予約ID,大人の数,子供の数,週末の宿泊数,平日の宿泊数,食事プランの種類,駐車場の要不要,予約された部屋のタイプ,予約日から到着日までの日数,マーケットセグメント,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,特別リクエストの数,予約ステータス,到着年/月/日
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,65.00,0,Not_Canceled,2017-10-02
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,Not_Canceled,2018-11-06
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,Online,0,0,0,60.00,0,Canceled,2018-02-28
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,Online,0,0,0,100.00,0,Canceled,2018-05-20
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,Online,0,0,0,94.50,0,Canceled,2018-04-11

### 予約ID列の削除

In [19]:
#予約IDの削除
df_renamed.drop("予約ID",inplace=True,axis=1)

### 食事プランの種類を日本語に変換

In [20]:
#食事プランの種類の中身を日本語に変換
df_renamed["食事プランの種類"].unique()

meal_plan_mapping = {
    'Meal Plan 1': 'プラン1',
    'Meal Plan 2': 'プラン2',
    'Meal Plan 3': 'プラン3',
    'Not Selected': '選択なし'
}

df_renamed['食事プランの種類'] = df_renamed['食事プランの種類'].replace(meal_plan_mapping)

print(df_renamed['食事プランの種類'].value_counts())

食事プランの種類
プラン1    27835
選択なし     5130
プラン2     3305
プラン3        5
Name: count, dtype: int64

### 予約された部屋のタイプを日本語に変換

In [21]:
#予約された部屋のタイプを日本語に変換
df_renamed["予約された部屋のタイプ"].unique()

array(['Room_Type 1', 'Room_Type 4', 'Room_Type 2', 'Room_Type 6',
       'Room_Type 5', 'Room_Type 7', 'Room_Type 3'], dtype=object)

In [22]:
room_type_mapping = {
'Room_Type 1':"タイプ1", 
'Room_Type 4':'タイプ4',
'Room_Type 2':"タイプ2",
'Room_Type 6':"タイプ6",
'Room_Type 5':"タイプ5",
'Room_Type 7':"タイプ7", 
'Room_Type 3':"タイプ3",
}

df_renamed["予約された部屋のタイプ"] = df_renamed["予約された部屋のタイプ"].replace(room_type_mapping)

print(df_renamed['予約された部屋のタイプ'].value_counts())

予約された部屋のタイプ
タイプ1    28130
タイプ4     6057
タイプ6      966
タイプ2      692
タイプ5      265
タイプ7      158
タイプ3        7
Name: count, dtype: int64

### マーケットセグメントの日本語変換

In [23]:


df_renamed["マーケットセグメント"].unique()

array(['Offline', 'Online', 'Corporate', 'Aviation', 'Complementary'],
      dtype=object)

In [24]:


segment_mapping = {
    "Offline":"オフライン予約",
    "Online":"オンライン予約",
    "Corporate":"法人予約",
    "Aviation":"航空",
    "Complementary":"招待",
}

df_renamed["マーケットセグメント"] = df_renamed["マーケットセグメント"].replace(segment_mapping)

print(df_renamed["マーケットセグメント"].value_counts())

マーケットセグメント
オンライン予約    23214
オフライン予約    10528
法人予約        2017
招待           391
航空           125
Name: count, dtype: int64

### 目的変数のクラスラベル化

In [25]:
df_renamed["予約ステータス"].unique()

status_mapping = {
    "Not_Canceled":0,
    "Canceled":1,
}

df_renamed["予約ステータス"] = df_renamed["予約ステータス"].replace(status_mapping)
print(df_renamed["予約ステータス"].value_counts())

予約ステータス
0    24390
1    11885
Name: count, dtype: int64

/tmp/ipykernel_1660/929377365.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_renamed["予約ステータス"] = df_renamed["予約ステータス"].replace(status_mapping)

In [26]:
#型の確認
df_renamed.dtypes

大人の数                          int64
子供の数                          int64
週末の宿泊数                        int64
平日の宿泊数                        int64
食事プランの種類                     object
駐車場の要不要                       int64
予約された部屋のタイプ                  object
予約日から到着日までの日数                 int64
マーケットセグメント                   object
リピーター客                        int64
過去のキャンセル回数                    int64
過去のキャンセルされなかった予約数             int64
一泊あたりの宿泊費                   float64
特別リクエストの数                     int64
予約ステータス                       int64
到着年/月/日              datetime64[ns]
dtype: object

In [27]:
file_path = 'cleaned_hotel_data.csv'

df_renamed.to_csv(
    file_path, 
    index=False,      # インデックス列をCSVファイルに含めない
    encoding='utf-8'  # 日本語や特殊文字を含む場合はUTF-8を推奨
)

print(f"データが '{file_path}' として保存されました。")

データが 'cleaned_hotel_data.csv' として保存されました。

### 課題設定
- どのような顧客がキャンセル率が高いか
- 売り上げを向上させるには、どのような顧客にターゲットを当てるべきか、また、具体的に改善するべきことはあるか。

In [28]:
df_renamed.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,食事プランの種類,駐車場の要不要,予約された部屋のタイプ,予約日から到着日までの日数,マーケットセグメント,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,特別リクエストの数,予約ステータス,到着年/月/日
0,2,0,1,2,プラン1,0,タイプ1,224,オフライン予約,0,0,0,65.00,0,0,2017-10-02
1,2,0,2,3,選択なし,0,タイプ1,5,オンライン予約,0,0,0,106.68,1,0,2018-11-06
2,1,0,2,1,プラン1,0,タイプ1,1,オンライン予約,0,0,0,60.00,0,1,2018-02-28
3,2,0,0,2,プラン1,0,タイプ1,211,オンライン予約,0,0,0,100.00,0,1,2018-05-20
4,2,0,1,1,選択なし,0,タイプ1,48,オンライン予約,0,0,0,94.50,0,1,2018-04-11

### 機械学習モデル用前処理

In [59]:
import pandas as pd
import numpy as np

df = pd.read_csv("/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data/Hotel Reservations.csv")

new_columns = {
"Booking_ID":"予約ID",
"no_of_adults":"大人の数",
"no_of_children":"子供の数",
"no_of_weekend_nights":"週末の宿泊数",
"no_of_week_nights":"平日の宿泊数",
"type_of_meal_plan":"食事プランの種類",
"required_car_parking_space":"駐車場の要不要",
"room_type_reserved":"予約された部屋のタイプ",
"lead_time":"予約日から到着日までの日数",
"arrival_year":"到着年",
"arrival_month":"到着月",
"arrival_date":"到着日",
"market_segment_type":"マーケットセグメント",
"repeated_guest":"リピーター客",
"no_of_previous_cancellations":"過去のキャンセル回数",
"no_of_previous_bookings_not_canceled":"過去のキャンセルされなかった予約数",
"avg_price_per_room":"一泊あたりの宿泊費",
"no_of_special_requests":"特別リクエストの数",
"booking_status":"予約ステータス",
}

df_renamed = df.rename(columns=new_columns)

#予約IDの削除
df_renamed.drop("予約ID",inplace=True,axis=1)

#食事プランの種類の中身を日本語に変換
meal_plan_mapping = {
    'Meal Plan 1': 'プラン1',
    'Meal Plan 2': 'プラン2',
    'Meal Plan 3': 'プラン3',
    'Not Selected': '選択なし'
}

df_renamed['食事プランの種類'] = df_renamed['食事プランの種類'].replace(meal_plan_mapping)

#部屋タイプを日本後に変換
room_type_mapping = {
'Room_Type 1':"タイプ1", 
'Room_Type 4':'タイプ4',
'Room_Type 2':"タイプ2",
'Room_Type 6':"タイプ6",
'Room_Type 5':"タイプ5",
'Room_Type 7':"タイプ7", 
'Room_Type 3':"タイプ3",
}

df_renamed["予約された部屋のタイプ"] = df_renamed["予約された部屋のタイプ"].replace(room_type_mapping)

#マーケットセグメントの日本語変換
segment_mapping = {
    "Offline":"オフライン予約",
    "Online":"オンライン予約",
    "Corporate":"法人予約",
    "Aviation":"航空",
    "Complementary":"招待",
}

df_renamed["マーケットセグメント"] = df_renamed["マーケットセグメント"].replace(segment_mapping)

#目的変数のクラスラベル化
status_mapping = {
    "Not_Canceled":0,
    "Canceled":1,
}

df_renamed["予約ステータス"] = df_renamed["予約ステータス"].replace(status_mapping)

df_renamed.head()

/tmp/ipykernel_1660/1415015753.py:73: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_renamed["予約ステータス"] = df_renamed["予約ステータス"].replace(status_mapping)

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,食事プランの種類,駐車場の要不要,予約された部屋のタイプ,予約日から到着日までの日数,到着年,到着月,到着日,マーケットセグメント,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,特別リクエストの数,予約ステータス
0,2,0,1,2,プラン1,0,タイプ1,224,2017,10,2,オフライン予約,0,0,0,65.00,0,0
1,2,0,2,3,選択なし,0,タイプ1,5,2018,11,6,オンライン予約,0,0,0,106.68,1,0
2,1,0,2,1,プラン1,0,タイプ1,1,2018,2,28,オンライン予約,0,0,0,60.00,0,1
3,2,0,0,2,プラン1,0,タイプ1,211,2018,5,20,オンライン予約,0,0,0,100.00,0,1
4,2,0,1,1,選択なし,0,タイプ1,48,2018,4,11,オンライン予約,0,0,0,94.50,0,1

In [ ]:
df_renamed.head()

In [60]:
import pandas as pd

# 変換したいカテゴリ変数を持つ列のリスト
categorical_cols = ["食事プランの種類", "予約された部屋のタイプ", 'マーケットセグメント',] 

# One-Hot Encodingを実行
df_encoded = pd.get_dummies(
    df_renamed, 
    columns=categorical_cols, 
    drop_first=True # ダミー変数トラップ回避のため、最初のカテゴリを削除
)

# 元のカテゴリ列は自動で新しいダミー変数に置き換えられます
print(df_encoded.head())

   大人の数  子供の数  週末の宿泊数  平日の宿泊数  駐車場の要不要  予約日から到着日までの日数   到着年  到着月  到着日  リピーター客  \
0     2     0       1       2        0            224  2017   10    2       0
1     2     0       2       3        0              5  2018   11    6       0
2     1     0       2       1        0              1  2018    2   28       0
3     2     0       0       2        0            211  2018    5   20       0
4     2     0       1       1        0             48  2018    4   11       0

   ...  予約された部屋のタイプ_タイプ2  予約された部屋のタイプ_タイプ3  予約された部屋のタイプ_タイプ4  \
0  ...             False             False             False
1  ...             False             False             False
2  ...             False             False             False
3  ...             False             False             False
4  ...             False             False             False

   予約された部屋のタイプ_タイプ5  予約された部屋のタイプ_タイプ6  予約された部屋のタイプ_タイプ7  マーケットセグメント_オンライン予約  \
0             False             False             False               False
1             False             False             False                True
2             False             False             False                True
3             False             False             False                True
4             False             False             False                True

   マーケットセグメント_招待  マーケットセグメント_法人予約  マーケットセグメント_航空
0          False            False          False
1          False            False          False
2          False            False          False
3          False            False          False
4          False            False          False

[5 rows x 28 columns]

In [61]:
df_encoded['到着年/月/日'] = (
    df_encoded['到着年'].astype(str) + '-' + 
    df_encoded['到着月'].astype(str) + '-' + 
    df_encoded['到着日'].astype(str)
)

#df_encoded["到着年/月/日"] = pd.to_datetime(df_encoded["到着年/月/日"],errors="coerce")
#df_encoded[["到着年","到着月","到着日"]].drop(axis=1,inplace=True)

#df_encoded.head()

In [62]:
df_encoded["到着年/月/日"] = pd.to_datetime(df_encoded["到着年/月/日"],errors="coerce")

In [63]:
df_encoded.drop(columns=["到着年","到着月","到着日"],axis=1,inplace=True)

In [64]:
df_encoded.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,駐車場の要不要,予約日から到着日までの日数,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,...,予約された部屋のタイプ_タイプ3,予約された部屋のタイプ_タイプ4,予約された部屋のタイプ_タイプ5,予約された部屋のタイプ_タイプ6,予約された部屋のタイプ_タイプ7,マーケットセグメント_オンライン予約,マーケットセグメント_招待,マーケットセグメント_法人予約,マーケットセグメント_航空,到着年/月/日
0,2,0,1,2,0,224,0,0,0,65.00,...,False,False,False,False,False,False,False,False,False,2017-10-02
1,2,0,2,3,0,5,0,0,0,106.68,...,False,False,False,False,False,True,False,False,False,2018-11-06
2,1,0,2,1,0,1,0,0,0,60.00,...,False,False,False,False,False,True,False,False,False,2018-02-28
3,2,0,0,2,0,211,0,0,0,100.00,...,False,False,False,False,False,True,False,False,False,2018-05-20
4,2,0,1,1,0,48,0,0,0,94.50,...,False,False,False,False,False,True,False,False,False,2018-04-11

In [ ]:
df_encoded["到着月"] = df_encoded["到着年/月/日"].dt.month
df_encoded["到着年"] = df_encoded["到着年/月/日"].dt.year
df_encoded.head()

In [66]:
df_encoded.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,駐車場の要不要,予約日から到着日までの日数,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,...,予約された部屋のタイプ_タイプ3,予約された部屋のタイプ_タイプ4,予約された部屋のタイプ_タイプ5,予約された部屋のタイプ_タイプ6,予約された部屋のタイプ_タイプ7,マーケットセグメント_オンライン予約,マーケットセグメント_招待,マーケットセグメント_法人予約,マーケットセグメント_航空,到着年/月/日
0,2,0,1,2,0,224,0,0,0,65.00,...,False,False,False,False,False,False,False,False,False,2017-10-02
1,2,0,2,3,0,5,0,0,0,106.68,...,False,False,False,False,False,True,False,False,False,2018-11-06
2,1,0,2,1,0,1,0,0,0,60.00,...,False,False,False,False,False,True,False,False,False,2018-02-28
3,2,0,0,2,0,211,0,0,0,100.00,...,False,False,False,False,False,True,False,False,False,2018-05-20
4,2,0,1,1,0,48,0,0,0,94.50,...,False,False,False,False,False,True,False,False,False,2018-04-11

In [67]:
df_encoded.dtypes

大人の数                           int64
子供の数                           int64
週末の宿泊数                         int64
平日の宿泊数                         int64
駐車場の要不要                        int64
予約日から到着日までの日数                  int64
リピーター客                         int64
過去のキャンセル回数                     int64
過去のキャンセルされなかった予約数              int64
一泊あたりの宿泊費                    float64
特別リクエストの数                      int64
予約ステータス                        int64
食事プランの種類_プラン2                   bool
食事プランの種類_プラン3                   bool
食事プランの種類_選択なし                   bool
予約された部屋のタイプ_タイプ2                bool
予約された部屋のタイプ_タイプ3                bool
予約された部屋のタイプ_タイプ4                bool
予約された部屋のタイプ_タイプ5                bool
予約された部屋のタイプ_タイプ6                bool
予約された部屋のタイプ_タイプ7                bool
マーケットセグメント_オンライン予約              bool
マーケットセグメント_招待                   bool
マーケットセグメント_法人予約                 bool
マーケットセグメント_航空                   bool
到着年/月/日               datetime64[ns]
dtype: object

In [68]:
df_encoded["到着月"] = df_encoded["到着年/月/日"].dt.month
df_encoded["到着年"] = df_encoded["到着年/月/日"].dt.year
df_encoded.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,駐車場の要不要,予約日から到着日までの日数,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,...,予約された部屋のタイプ_タイプ5,予約された部屋のタイプ_タイプ6,予約された部屋のタイプ_タイプ7,マーケットセグメント_オンライン予約,マーケットセグメント_招待,マーケットセグメント_法人予約,マーケットセグメント_航空,到着年/月/日,到着月,到着年
0,2,0,1,2,0,224,0,0,0,65.00,...,False,False,False,False,False,False,False,2017-10-02,10.0,2017.0
1,2,0,2,3,0,5,0,0,0,106.68,...,False,False,False,True,False,False,False,2018-11-06,11.0,2018.0
2,1,0,2,1,0,1,0,0,0,60.00,...,False,False,False,True,False,False,False,2018-02-28,2.0,2018.0
3,2,0,0,2,0,211,0,0,0,100.00,...,False,False,False,True,False,False,False,2018-05-20,5.0,2018.0
4,2,0,1,1,0,48,0,0,0,94.50,...,False,False,False,True,False,False,False,2018-04-11,4.0,2018.0

In [69]:
# 例: 欠損行を削除
df_encoded.dropna(subset=['到着月'], inplace=True)
df_encoded.dropna(subset=['到着年'], inplace=True)
# Step 2: 整数型に変換
df_encoded["到着月"] = df_encoded['到着月'].astype(int)
df_encoded["到着年"] = df_encoded['到着年'].astype(int)

In [70]:
import pandas as pd

# 変換したいカテゴリ変数を持つ列のリスト
categorical_cols = ["到着年","到着月"]

# One-Hot Encodingを実行
df_encoded = pd.get_dummies(
    df_encoded, 
    columns=categorical_cols, 
    drop_first=True # ダミー変数トラップ回避のため、最初のカテゴリを削除
)

# 元のカテゴリ列は自動で新しいダミー変数に置き換えられます
print(df_encoded.head())

   大人の数  子供の数  週末の宿泊数  平日の宿泊数  駐車場の要不要  予約日から到着日までの日数  リピーター客  過去のキャンセル回数  \
0     2     0       1       2        0            224       0           0
1     2     0       2       3        0              5       0           0
2     1     0       2       1        0              1       0           0
3     2     0       0       2        0            211       0           0
4     2     0       1       1        0             48       0           0

   過去のキャンセルされなかった予約数  一泊あたりの宿泊費  ...  到着月_3  到着月_4  到着月_5  到着月_6  到着月_7  \
0                  0      65.00  ...  False  False  False  False  False
1                  0     106.68  ...  False  False  False  False  False
2                  0      60.00  ...  False  False  False  False  False
3                  0     100.00  ...  False  False   True  False  False
4                  0      94.50  ...  False   True  False  False  False

   到着月_8  到着月_9  到着月_10  到着月_11  到着月_12
0  False  False    True   False   False
1  False  False   False    True   False
2  False  False   False   False   False
3  False  False   False   False   False
4  False  False   False   False   False

[5 rows x 38 columns]

In [43]:
df_encoded.columns

Index(['大人の数', '子供の数', '週末の宿泊数', '平日の宿泊数', '駐車場の要不要', '予約日から到着日までの日数',
       'リピーター客', '過去のキャンセル回数', '過去のキャンセルされなかった予約数', '一泊あたりの宿泊費', '特別リクエストの数',
       '予約ステータス', '食事プランの種類_プラン2', '食事プランの種類_プラン3', '食事プランの種類_選択なし',
       '予約された部屋のタイプ_タイプ2', '予約された部屋のタイプ_タイプ3', '予約された部屋のタイプ_タイプ4',
       '予約された部屋のタイプ_タイプ5', '予約された部屋のタイプ_タイプ6', '予約された部屋のタイプ_タイプ7',
       'マーケットセグメント_オンライン予約', 'マーケットセグメント_招待', 'マーケットセグメント_法人予約',
       'マーケットセグメント_航空', '到着年/月/日', '到着年_2018', '到着月_2', '到着月_3', '到着月_4',
       '到着月_5', '到着月_6', '到着月_7', '到着月_8', '到着月_9', '到着月_10', '到着月_11',
       '到着月_12'],
      dtype='object')

In [71]:
df_encoded.drop(columns="到着年/月/日",axis=1,inplace=True)
df_encoded.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,駐車場の要不要,予約日から到着日までの日数,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,...,到着月_3,到着月_4,到着月_5,到着月_6,到着月_7,到着月_8,到着月_9,到着月_10,到着月_11,到着月_12
0,2,0,1,2,0,224,0,0,0,65.00,...,False,False,False,False,False,False,False,True,False,False
1,2,0,2,3,0,5,0,0,0,106.68,...,False,False,False,False,False,False,False,False,True,False
2,1,0,2,1,0,1,0,0,0,60.00,...,False,False,False,False,False,False,False,False,False,False
3,2,0,0,2,0,211,0,0,0,100.00,...,False,False,True,False,False,False,False,False,False,False
4,2,0,1,1,0,48,0,0,0,94.50,...,False,True,False,False,False,False,False,False,False,False

In [49]:
from sklearn.model_selection import train_test_split
import pandas as pd
X = df_encoded.drop(columns="予約ステータス",axis=1)
y = df_encoded["予約ステータス"]

# データ分割の実行
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.3, # テストデータの割合を30%に設定
    random_state=42,
    stratify=y  # 乱数シードを設定し、結果の再現性を確保
)

# 結果の確認（各セットのサイズ）
print(f"X_trainのサイズ: {X_train.shape}")
print(f"X_testのサイズ: {X_test.shape}")

X_trainのサイズ: (25366, 36)
X_testのサイズ: (10872, 36)

In [ ]:
from Logistic_pipeline import fit_predict_evaluate

# パイプラインを実行
lr_model, lr_report, lr_coefficients = fit_predict_evaluate(
    X_train, X_test, y_train, y_test, C=0.5
)

# 評価レポートの表示
print("\n=== ロジスティック回帰 評価レポート ===")
print(lr_report)

# 特徴量の影響度（係数）トップ10の表示
print("\n=== 特徴量の影響度（係数）トップ10 ===")
print(lr_coefficients.head(10))

--- モデル学習開始 ---
--- 学習完了 ---

=== ロジスティック回帰 評価レポート ===
              precision    recall  f1-score   support

     キャンセルなし       0.83      0.89      0.86      7308
     キャンセルあり       0.74      0.64      0.68      3564

    accuracy                           0.81     10872
   macro avg       0.78      0.76      0.77     10872
weighted avg       0.80      0.81      0.80     10872


=== 特徴量の影響度（係数）トップ10 ===
               Feature  Coefficient
20  マーケットセグメント_オンライン予約     1.822890
23       マーケットセグメント_航空     1.768046
25               到着月_2     1.644874
34              到着月_11     1.405978
26               到着月_3     1.339457
33              到着月_10     1.114449
27               到着月_4     1.109713
29               到着月_6     1.041085
30               到着月_7     0.993189
22     マーケットセグメント_法人予約     0.970892

In [54]:
df_encoded.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,駐車場の要不要,予約日から到着日までの日数,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,...,到着月_3,到着月_4,到着月_5,到着月_6,到着月_7,到着月_8,到着月_9,到着月_10,到着月_11,到着月_12
0,2,0,1,2,0,224,0,0,0,65.00,...,False,False,False,False,False,False,False,True,False,False
1,2,0,2,3,0,5,0,0,0,106.68,...,False,False,False,False,False,False,False,False,True,False
2,1,0,2,1,0,1,0,0,0,60.00,...,False,False,False,False,False,False,False,False,False,False
3,2,0,0,2,0,211,0,0,0,100.00,...,False,False,True,False,False,False,False,False,False,False
4,2,0,1,1,0,48,0,0,0,94.50,...,False,True,False,False,False,False,False,False,False,False

In [55]:
df_encoded["宿泊人数"] = df_encoded["大人の数"] + df_encoded["子供の数"]
df_encoded.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,駐車場の要不要,予約日から到着日までの日数,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,...,到着月_4,到着月_5,到着月_6,到着月_7,到着月_8,到着月_9,到着月_10,到着月_11,到着月_12,宿泊人数
0,2,0,1,2,0,224,0,0,0,65.00,...,False,False,False,False,False,False,True,False,False,2
1,2,0,2,3,0,5,0,0,0,106.68,...,False,False,False,False,False,False,False,True,False,2
2,1,0,2,1,0,1,0,0,0,60.00,...,False,False,False,False,False,False,False,False,False,1
3,2,0,0,2,0,211,0,0,0,100.00,...,False,True,False,False,False,False,False,False,False,2
4,2,0,1,1,0,48,0,0,0,94.50,...,True,False,False,False,False,False,False,False,False,2

In [56]:
from data_preprocessing import split_data 

X = df_encoded.drop(columns="予約ステータス",axis=1)
y = df_encoded["予約ステータス"]

X_train,X_test,y_train,y_test = split_data(X,y,test_ratio=0.3)

from Logistic_pipeline import fit_predict_evaluate

# パイプラインを実行
lr_model, lr_report, lr_coefficients = fit_predict_evaluate(
    X_train, X_test, y_train, y_test, C=0.5
)

# 評価レポートの表示
print("\n=== ロジスティック回帰 評価レポート ===")
print(lr_report)

# 特徴量の影響度（係数）トップ10の表示
print("\n=== 特徴量の影響度（係数）トップ10 ===")
print(lr_coefficients.head(10))

データ分割完了: Train=25366, Test=10872
--- モデル学習開始 ---
--- 学習完了 ---

=== ロジスティック回帰 評価レポート ===
              precision    recall  f1-score   support

     キャンセルなし       0.83      0.89      0.86      7308
     キャンセルあり       0.73      0.64      0.68      3564

    accuracy                           0.81     10872
   macro avg       0.78      0.76      0.77     10872
weighted avg       0.80      0.81      0.80     10872


=== 特徴量の影響度（係数）トップ10 ===
               Feature  Coefficient
20  マーケットセグメント_オンライン予約     1.823221
23       マーケットセグメント_航空     1.774160
25               到着月_2     1.647514
34              到着月_11     1.408923
26               到着月_3     1.342939
33              到着月_10     1.119137
27               到着月_4     1.113239
29               到着月_6     1.045925
30               到着月_7     0.997155
22     マーケットセグメント_法人予約     0.971795

### 到着日までの日数の標準化

In [73]:
from sklearn.preprocessing import StandardScaler

# StandardScalerのインスタンス化
scaler = StandardScaler()

# X_train の統計量（平均と標準偏差）を学習
lead_time_std = scaler.fit_transform(X_train[["予約日から到着日までの日数"]])

In [75]:
X_train["予約日から到着日までの日数"] = lead_time_std
X_train.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,駐車場の要不要,予約日から到着日までの日数,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,...,到着月_4,到着月_5,到着月_6,到着月_7,到着月_8,到着月_9,到着月_10,到着月_11,到着月_12,宿泊人数
16220,2,0,1,4,0,2.243703,0,0,0,71.23,...,False,False,False,False,False,False,False,False,True,2
22067,2,0,2,2,0,0.207989,0,0,0,125.00,...,False,False,False,False,False,False,False,False,True,2
12376,2,0,0,3,0,-0.013032,0,0,0,76.50,...,False,False,False,False,True,False,False,False,False,2
10074,2,0,3,5,0,1.487580,0,0,0,119.85,...,False,False,False,False,False,True,False,False,False,2
3785,2,0,1,1,0,-0.862215,0,0,0,154.00,...,False,False,False,False,False,True,False,False,False,2

In [76]:
lead_time_std_test = scaler.transform(X_test[["予約日から到着日までの日数"]])
X_test["予約日から到着日までの日数"] = lead_time_std_test

In [77]:
from data_preprocessing import split_data 

X = df_encoded.drop(columns="予約ステータス",axis=1)
y = df_encoded["予約ステータス"]

X_train,X_test,y_train,y_test = split_data(X,y,test_ratio=0.3)

from Logistic_pipeline import fit_predict_evaluate

# パイプラインを実行
lr_model, lr_report, lr_coefficients = fit_predict_evaluate(
    X_train, X_test, y_train, y_test, C=0.5
)

# 評価レポートの表示
print("\n=== ロジスティック回帰 評価レポート ===")
print(lr_report)

# 特徴量の影響度（係数）トップ10の表示
print("\n=== 特徴量の影響度（係数）トップ10 ===")
print(lr_coefficients.head(10))

データ分割完了: Train=25366, Test=10872
--- モデル学習開始 ---
--- 学習完了 ---

=== ロジスティック回帰 評価レポート ===
              precision    recall  f1-score   support

     キャンセルなし       0.83      0.89      0.86      7308
     キャンセルあり       0.74      0.64      0.68      3564

    accuracy                           0.81     10872
   macro avg       0.78      0.76      0.77     10872
weighted avg       0.80      0.81      0.80     10872


=== 特徴量の影響度（係数）トップ10 ===
               Feature  Coefficient
20  マーケットセグメント_オンライン予約     1.822890
23       マーケットセグメント_航空     1.768046
25               到着月_2     1.644874
34              到着月_11     1.405978
26               到着月_3     1.339457
33              到着月_10     1.114449
27               到着月_4     1.109713
29               到着月_6     1.041085
30               到着月_7     0.993189
22     マーケットセグメント_法人予約     0.970892