In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from data_preprocessing import preprocessing_pipeline,new_columns,columns_mappings_dict,categorical_cols,int_cols
from Logistic_pipeline import fit_predict_evaluate

### ベンチマークモデル

In [3]:
df = pd.read_csv("/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data/Hotel Reservations.csv")

In [4]:
X_train,X_test,y_train,y_test = preprocessing_pipeline(
    df,new_columns,columns_mappings_dict,categorical_cols,int_cols
)

/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data_preprocessing.py:91: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_renamed[col] = df_renamed[col].replace(maps)

In [5]:
X_train.head()

,大人の数,子供の数,週末の宿泊数,平日の宿泊数,駐車場の要不要,予約日から到着日までの日数,リピーター客,過去のキャンセル回数,過去のキャンセルされなかった予約数,一泊あたりの宿泊費,...,到着月_2,到着月_3,到着月_4,到着月_5,到着月_7,到着月_8,到着月_9,到着月_10,到着月_11,到着月_12
11731,0.298918,-0.26463,1.362393,-0.141380,0,6,0,-0.063684,-0.089459,-1.009423,...,False,False,False,False,False,False,False,False,False,True
35609,0.298918,-0.26463,0.214274,1.278289,0,148,0,-0.063684,-0.089459,-1.037878,...,False,False,False,False,False,False,False,False,False,True
21639,0.298918,-0.26463,1.362393,1.988124,0,195,0,-0.063684,-0.089459,-0.356376,...,False,False,False,False,True,False,False,False,False,False
24432,-1.626204,-0.26463,-0.933846,0.568455,0,93,0,-0.063684,-0.089459,0.282443,...,False,False,False,False,False,False,False,True,False,False
31975,0.298918,-0.26463,0.214274,-0.141380,0,305,0,-0.063684,-0.089459,-0.411864,...,False,False,False,False,False,False,False,False,True,False

In [6]:
lr_model, lr_report, lr_coefficients = fit_predict_evaluate(X_train,X_test,y_train,y_test)

# 評価レポートの表示
print("\n=== ロジスティック回帰 評価レポート ===")
print(lr_report)

# 特徴量の影響度（係数）トップ10の表示
print("\n=== 特徴量の影響度（係数）トップ10 ===")
lr_coefficients

--- モデル学習開始 ---
--- 学習完了 ---

=== ロジスティック回帰 評価レポート ===
              precision    recall  f1-score   support

     キャンセルなし       0.84      0.90      0.87      4878
     キャンセルあり       0.76      0.66      0.70      2377

    accuracy                           0.82      7255
   macro avg       0.80      0.78      0.79      7255
weighted avg       0.81      0.82      0.81      7255


=== 特徴量の影響度（係数）トップ10 ===

               Feature  Coefficient
23       マーケットセグメント_航空     0.935628
21  マーケットセグメント_オンライン予約     0.786492
9            一泊あたりの宿泊費     0.630324
26               到着月_2     0.590970
24            到着年_2018     0.485736
13       食事プランの種類_プラン3     0.476824
34              到着月_11     0.412025
27               到着月_3     0.317104
15    予約された部屋のタイプ_タイプ3     0.142781
2               週末の宿泊数     0.141163
7           過去のキャンセル回数     0.102518
28               到着月_4     0.091678
33              到着月_10     0.078764
3               平日の宿泊数     0.075635
1                 子供の数     0.068440
0                 大人の数     0.067762
5        予約日から到着日までの日数     0.015774
12       食事プランの種類_プラン2    -0.044354
30               到着月_7    -0.103598
31               到着月_8    -0.156669
16    予約された部屋のタイプ_タイプ4    -0.218001
32               到着月_9    -0.240065
11       食事プランの種類_プラン1    -0.259096
14    予約された部屋のタイプ_タイプ2    -0.260509
29               到着月_5    -0.263803
8    過去のキャンセルされなかった予約数    -0.294088
18    予約された部屋のタイプ_タイプ6    -0.815757
17    予約された部屋のタイプ_タイプ5    -0.819624
20  マーケットセグメント_オフライン予約    -0.995227
10           特別リクエストの数    -1.180216
19    予約された部屋のタイプ_タイプ7    -1.310021
35              到着月_12    -1.481097
4              駐車場の要不要    -1.512025
22       マーケットセグメント_招待    -1.732826
6               リピーター客    -1.986410
25               到着月_1    -2.165574

# 特徴量エンジニアリング

In [6]:
df = pd.read_csv("/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data/Hotel Reservations.csv")
X_train,X_test,y_train,y_test = preprocessing_pipeline(
    df,new_columns,columns_mappings_dict,categorical_cols
)

/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data_preprocessing.py:81: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_renamed[col] = df_renamed[col].replace(maps)

### 合計宿泊数の追加

In [7]:
X_train["合計宿泊数"] = X_train["平日の宿泊数"] + X_train["週末の宿泊数"]
X_test["合計宿泊数"] = X_test["平日の宿泊数"] + X_test["週末の宿泊数"]

In [8]:
lr_model, lr_report, lr_coefficients = fit_predict_evaluate(X_train,X_test,y_train,y_test)

# 評価レポートの表示
print("\n=== ロジスティック回帰 評価レポート ===")
print(lr_report)

# 特徴量の影響度（係数）トップ10の表示
print("\n=== 特徴量の影響度（係数）トップ10 ===")
lr_coefficients

--- モデル学習開始 ---
--- 学習完了 ---

=== ロジスティック回帰 評価レポート ===
              precision    recall  f1-score   support

     キャンセルなし       0.84      0.90      0.87      4878
     キャンセルあり       0.76      0.66      0.70      2377

    accuracy                           0.82      7255
   macro avg       0.80      0.78      0.79      7255
weighted avg       0.82      0.82      0.82      7255


=== 特徴量の影響度（係数）トップ10 ===

               Feature  Coefficient
5        予約日から到着日までの日数     1.356739
23       マーケットセグメント_航空     0.936330
21  マーケットセグメント_オンライン予約     0.795723
26               到着月_2     0.590401
24            到着年_2018     0.487420
34              到着月_11     0.412671
27               到着月_3     0.318182
7           過去のキャンセル回数     0.305090
13       食事プランの種類_プラン3     0.268072
1                 子供の数     0.169880
0                 大人の数     0.124876
28               到着月_4     0.092449
2               週末の宿泊数     0.089772
15    予約された部屋のタイプ_タイプ3     0.086188
33              到着月_10     0.079972
36               合計宿泊数     0.071333
9            一泊あたりの宿泊費     0.017851
3               平日の宿泊数    -0.018439
12       食事プランの種類_プラン2    -0.041599
30               到着月_7    -0.101025
31               到着月_8    -0.153326
8    過去のキャンセルされなかった予約数    -0.173439
16    予約された部屋のタイプ_タイプ4    -0.214653
32               到着月_9    -0.236501
11       食事プランの種類_プラン1    -0.258245
14    予約された部屋のタイプ_タイプ2    -0.261213
29               到着月_5    -0.261385
18    予約された部屋のタイプ_タイプ6    -0.808207
17    予約された部屋のタイプ_タイプ5    -0.819403
20  マーケットセグメント_オフライン予約    -0.987670
19    予約された部屋のタイプ_タイプ7    -1.310155
22       マーケットセグメント_招待    -1.379217
35              到着月_12    -1.479494
10           特別リクエストの数    -1.501518
4              駐車場の要不要    -1.509129
6               リピーター客    -1.972882
25               到着月_1    -2.150149

### 宿泊人数を追加

In [14]:
df = pd.read_csv("/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data/Hotel Reservations.csv")
X_train,X_test,y_train,y_test = preprocessing_pipeline(
    df,new_columns,columns_mappings_dict,categorical_cols
)

/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data_preprocessing.py:81: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_renamed[col] = df_renamed[col].replace(maps)

In [15]:
X_train["合計宿泊数"] = X_train["平日の宿泊数"] + X_train["週末の宿泊数"]
X_test["合計宿泊数"] = X_test["平日の宿泊数"] + X_test["週末の宿泊数"]

X_train["宿泊人数"] = X_train["大人の数"] + X_train["子供の数"]
X_test["宿泊人数"] = X_test["大人の数"] + X_test["子供の数"]

In [16]:
lr_model, lr_report, lr_coefficients = fit_predict_evaluate(X_train,X_test,y_train,y_test)

# 評価レポートの表示
print("\n=== ロジスティック回帰 評価レポート ===")
print(lr_report)

# 特徴量の影響度（係数）トップ10の表示
print("\n=== 特徴量の影響度（係数）トップ10 ===")
lr_coefficients

--- モデル学習開始 ---
--- 学習完了 ---

=== ロジスティック回帰 評価レポート ===
              precision    recall  f1-score   support

     キャンセルなし       0.84      0.90      0.87      4878
     キャンセルあり       0.76      0.66      0.70      2377

    accuracy                           0.82      7255
   macro avg       0.80      0.78      0.79      7255
weighted avg       0.82      0.82      0.82      7255


=== 特徴量の影響度（係数）トップ10 ===

               Feature  Coefficient
5        予約日から到着日までの日数     1.356861
23       マーケットセグメント_航空     0.947956
21  マーケットセグメント_オンライン予約     0.792020
26               到着月_2     0.584016
24            到着年_2018     0.485149
34              到着月_11     0.408260
13       食事プランの種類_プラン3     0.377452
27               到着月_3     0.312334
7           過去のキャンセル回数     0.294508
15    予約された部屋のタイプ_タイプ3     0.117407
37                宿泊人数     0.098360
2               週末の宿泊数     0.090042
28               到着月_4     0.087637
33              到着月_10     0.076607
1                 子供の数     0.072226
36               合計宿泊数     0.071418
0                 大人の数     0.026134
9            一泊あたりの宿泊費     0.017810
3               平日の宿泊数    -0.018625
12       食事プランの種類_プラン2    -0.041198
30               到着月_7    -0.106081
8    過去のキャンセルされなかった予約数    -0.145539
31               到着月_8    -0.156493
16    予約された部屋のタイプ_タイプ4    -0.213348
32               到着月_9    -0.242187
11       食事プランの種類_プラン1    -0.258969
14    予約された部屋のタイプ_タイプ2    -0.262593
29               到着月_5    -0.265263
18    予約された部屋のタイプ_タイプ6    -0.804343
17    予約された部屋のタイプ_タイプ5    -0.811706
20  マーケットセグメント_オフライン予約    -0.993769
19    予約された部屋のタイプ_タイプ7    -1.266345
35              到着月_12    -1.484337
10           特別リクエストの数    -1.502484
4              駐車場の要不要    -1.509614
22       マーケットセグメント_招待    -1.628103
6               リピーター客    -2.095486
25               到着月_1    -2.175711

### 総費用の追加→不採用

In [17]:
df = pd.read_csv("/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data/Hotel Reservations.csv")
X_train,X_test,y_train,y_test = preprocessing_pipeline(
    df,new_columns,columns_mappings_dict,categorical_cols
)

X_train["合計宿泊数"] = X_train["平日の宿泊数"] + X_train["週末の宿泊数"]
X_test["合計宿泊数"] = X_test["平日の宿泊数"] + X_test["週末の宿泊数"]

X_train["宿泊人数"] = X_train["大人の数"] + X_train["子供の数"]
X_test["宿泊人数"] = X_test["大人の数"] + X_test["子供の数"]

X_train["総費用"] = X_train["一泊あたりの宿泊費"] * X_train["合計宿泊数"]
X_test["総費用"] = X_test["一泊あたりの宿泊費"] * X_test["合計宿泊数"]

/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data_preprocessing.py:81: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_renamed[col] = df_renamed[col].replace(maps)

In [ ]:
lr_model, lr_report, lr_coefficients = fit_predict_evaluate(X_train,X_test,y_train,y_test)

# 評価レポートの表示
print("\n=== ロジスティック回帰 評価レポート ===")
print(lr_report)

# 特徴量の影響度（係数）トップ10の表示
print("\n=== 特徴量の影響度（係数）トップ10 ===")
lr_coefficients

### 宿泊費用の標準化

In [2]:
df = pd.read_csv("/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data/Hotel Reservations.csv")
X_train,X_test,y_train,y_test = preprocessing_pipeline(
    df,new_columns,columns_mappings_dict,categorical_cols
)

X_train["合計宿泊数"] = X_train["平日の宿泊数"] + X_train["週末の宿泊数"]
X_test["合計宿泊数"] = X_test["平日の宿泊数"] + X_test["週末の宿泊数"]

X_train["宿泊人数"] = X_train["大人の数"] + X_train["子供の数"]
X_test["宿泊人数"] = X_test["大人の数"] + X_test["子供の数"]

lr_model, lr_report, lr_coefficients = fit_predict_evaluate(X_train,X_test,y_train,y_test)

# 評価レポートの表示
print("\n=== ロジスティック回帰 評価レポート ===")
print(lr_report)

# 特徴量の影響度（係数）トップ10の表示
print("\n=== 特徴量の影響度（係数）トップ10 ===")
lr_coefficients

/home/haruk/workspace/kaggle-ishiwata/kaggle/new_compettition/data_preprocessing.py:81: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_renamed[col] = df_renamed[col].replace(maps)

--- モデル学習開始 ---
--- 学習完了 ---

=== ロジスティック回帰 評価レポート ===
              precision    recall  f1-score   support

     キャンセルなし       0.84      0.90      0.87      4878
     キャンセルあり       0.76      0.66      0.70      2377

    accuracy                           0.82      7255
   macro avg       0.80      0.78      0.79      7255
weighted avg       0.82      0.82      0.82      7255


=== 特徴量の影響度（係数）トップ10 ===

               Feature  Coefficient
5        予約日から到着日までの日数     1.356789
23       マーケットセグメント_航空     0.957208
21  マーケットセグメント_オンライン予約     0.805427
9            一泊あたりの宿泊費     0.629831
26               到着月_2     0.595959
13       食事プランの種類_プラン3     0.540297
24            到着年_2018     0.491820
34              到着月_11     0.417251
27               到着月_3     0.321831
7           過去のキャンセル回数     0.299805
15    予約された部屋のタイプ_タイプ3     0.157267
37                宿泊人数     0.098808
28               到着月_4     0.095073
2               週末の宿泊数     0.089919
33              到着月_10     0.084672
36               合計宿泊数     0.071597
1                 子供の数     0.070337
0                 大人の数     0.028471
3               平日の宿泊数    -0.018322
12       食事プランの種類_プラン2    -0.037953
30               到着月_7    -0.097837
31               到着月_8    -0.150345
8    過去のキャンセルされなかった予約数    -0.179333
16    予約された部屋のタイプ_タイプ4    -0.218314
32               到着月_9    -0.233458
11       食事プランの種類_プラン1    -0.253906
29               到着月_5    -0.258971
14    予約された部屋のタイプ_タイプ2    -0.259664
18    予約された部屋のタイプ_タイプ6    -0.812854
17    予約された部屋のタイプ_タイプ5    -0.817411
20  マーケットセグメント_オフライン予約    -0.977618
19    予約された部屋のタイプ_タイプ7    -1.309370
35              到着月_12    -1.475024
10           特別リクエストの数    -1.503191
4              駐車場の要不要    -1.510142
22       マーケットセグメント_招待    -1.746949
6               リピーター客    -1.976373
25               到着月_1    -2.158917